### ISSUE TITLE
Any plans to provide sample codes for the quantization code for ConvNeXt?

### ISSUE THREAD

**Issue by detectRecog** [facebookresearch/ConvNeXt#20]
Actually, I tried to use torch.fx to quant ConvNeXt to see the performance after quantization. But I get this error: `TypeError: dequantize() takes no arguments (1 given)`. Could you please help?

```
import torch
from torch.quantization import quantize_fx
torch.backends.cudnn.enabled = False
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

device_cpu = torch.device("cpu")

save_ckpt_path = 'cn-fx.pt'
from models.convnext import convnext_tiny
model = convnext_tiny(False)
model.eval() # essential
model.to(device_cpu)
inp_size = (224,224)

res = model(torch.randn((1,3,inp_size[0],inp_size[1])).to(device_cpu))
print(res.shape)
graph_module = torch.fx.symbolic_trace(model)

qconfig_dict = {'': torch.quantization.get_default_qat_qconfig('qnnpack')}
# qconfig_dict = {'': torch.quantization.get_default_qat_qconfig('fbgemm')}
mp = quantize_fx.prepare_fx(graph_module, qconfig_dict)


def eval_fn(model, device=device_cpu):
    with torch.no_grad():
        model.to(device)
        for i in range(20):
            ims = torch.rand((1,3,224,224)).to(device)
            output = model(ims)

eval_fn(mp, device=device_cpu)
mq = quantize_fx.convert_fx(mp)

dummy_input = torch.rand(1, 3, inp_size[0], inp_size[1])
torchscript_model = torch.jit.trace(mq, dummy_input)
from torch.utils.mobile_optimizer import optimize_for_mobile
torchscript_model = optimize_for_mobile(torchscript_model)
torch.jit.save(torchscript_model, save_ckpt_path)
torchscript_model._save_for_lite_interpreter(save_ckpt_path.replace('.pt', '.ptl'))

```

**Comment by liuzhuang13** [comment]
We are not planning to add code on quantization, and we don't have the experiences on this subject. Sorry but I'm afraid we cannot help you on debugging this.

**Comment by s9xie** [comment]
I tried to run the code but got a different error about Size mismatch.
I guess it's related to the pytorch and fx version.

Let's leave this open and see if the community has some feedback.

**Comment by twwinniejiang** [comment]
I am encountering the following problems, please ask how to solve them?

Traceback (most recent call last):
  File "run_with_submitit.py", line 122, in <module>
    main()
  File "run_with_submitit.py", line 83, in main
    args.job_dir = get_shared_folder() / "%j"
  File "run_with_submitit.py", line 37, in get_shared_folder
    raise RuntimeError("No shared folder available")
RuntimeError: No shared folder available
