### ISSUE TITLE
您好，请问这是什么问题，谢谢~

### ISSUE THREAD

**Issue by lxwkobe24** [facebookresearch/ConvNeXt#28]
Traceback (most recent call last):
  File "run_with_submitit.py", line 122, in <module>
    main()
  File "run_with_submitit.py", line 113, in main
    args.dist_url = get_init_file().as_uri()
  File "run_with_submitit.py", line 41, in get_init_file
    os.makedirs(str(get_shared_folder()), exist_ok=True)
  File "run_with_submitit.py", line 37, in get_shared_folder
    raise RuntimeError("No shared folder available")
RuntimeError: No shared folder available

**Comment by liuzhuang13** [comment]
Are you running using a SLURM cluster? If not, you don't have to run the file `run_with_submitit.py`. You can follow our commands for single machine training.

**Comment by lxwkobe24** [comment]
> 您是否使用 SLURM 集群运行？如果没有，您不必运行该文件`run_with_submitit.py`。您可以按照我们的命令进行单机训练（以 开头的那些`python -m torch.distributed.launch --nproc_per_node=8 main.py`）

您好请问训练有要求什么显卡什么内存呢

**Comment by liuzhuang13** [comment]
You can adjust the `--update_freq` and `--batch_size` parameters to fit model into GPUs of any memory size. See our [TRAINING.md](https://github.com/facebookresearch/ConvNeXt/blob/main/TRAINING.md) for instructions.

**Comment by lxwkobe24** [comment]
> update_freq

Traceback (most recent call last):
  File "main.py", line 455, in <module>
    main(args)
  File "main.py", line 212, in main
    dataset_val, _ = build_dataset(is_train=False, args=args)
  File "/home/kas/ConvNeXt/datasets.py", line 40, in build_dataset
    dataset = datasets.ImageFolder(root, transform=transform)
  File "/home/kas/.conda/envs/convnext/lib/python3.8/site-packages/torchvision/datasets/folder.py", line 253, in __init__
    super(ImageFolder, self).__init__(root, loader, IMG_EXTENSIONS if is_valid_file is None else None,
  File "/home/kas/.conda/envs/convnext/lib/python3.8/site-packages/torchvision/datasets/folder.py", line 127, in __init__
    samples = self.make_dataset(self.root, class_to_idx, extensions, is_valid_file)
  File "/home/kas/.conda/envs/convnext/lib/python3.8/site-packages/torchvision/datasets/folder.py", line 149, in make_dataset
    return make_dataset(directory, class_to_idx, extensions=extensions, is_valid_file=is_valid_file)
  File "/home/kas/.conda/envs/convnext/lib/python3.8/site-packages/torchvision/datasets/folder.py", line 60, in make_dataset
    directory = os.path.expanduser(directory)
  File "/home/kas/.conda/envs/convnext/lib/python3.8/posixpath.py", line 231, in expanduser
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Killing subprocess 32241
Traceback (most recent call last):
  File "/home/kas/.conda/envs/convnext/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/kas/.conda/envs/convnext/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/kas/.conda/envs/convnext/lib/python3.8/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/kas/.conda/envs/convnext/lib/python3.8/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/kas/.conda/envs/convnext/lib/python3.8/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/kas/.conda/envs/convnext/bin/python', '-u', 'main.py', '--local_rank=0', '--model', 'convnext_tiny', '--drop_path', '0.1', '--batch_size', '1', '--lr', '4e-3', '--update_freq', '1', '--model_ema', 'true', '--model_ema_eval', 'true', '--data_path', '/home/kas/ConvNeXt/test', '--output_dir', '/home/kas/ConvNeXt/saveresults']' returned non-zero exit status 1.
您好请问这个是什么问题，我把路径都换成了绝对路径了

**Comment by liuzhuang13** [comment]
What command are you running? Can you paste it?

**Comment by lxwkobe24** [comment]
python -m torch.distributed.launch --nproc_per_node=1 main.py --model convnext_tiny --drop_path 0.1 --batch_size 1 --lr 4e-3 --update_freq 1 --model_ema true --model_ema_eval true --data_path /home/kas/ConvNeXt/test  --output_dir /home/kas/ConvNeXt/saveresults
hello , i use this command

**Comment by liuzhuang13** [comment]
Does your data_path exist? Does it contain ImageNet data? (`train` and `val` as subfolders).

**Comment by lxwkobe24** [comment]
> Does your data_path exist? Does it contain ImageNet data? (`train` and `val` as subfolders).

您好我是想训练自己的数据集的

**Comment by liuzhuang13** [comment]
You need to set `--data_set image_folder` (https://github.com/facebookresearch/ConvNeXt/issues/17). Make sure there are subfolders in your `data_path`, each being a class.

**Comment by lxwkobe24** [comment]
您好，我已经设置了对应路径了

**Comment by liuzhuang13** [comment]
your command did not set `data_set` variable.

**Comment by lxwkobe24** [comment]
您好，是需要加上--data_set image_folder吗

**Comment by liuzhuang13** [comment]
Yes. Please look trace the error in the code before asking further questions. Thanks

**Comment by lxwkobe24** [comment]
thanks ,so much

**Comment by lxwkobe24** [comment]
我试试，谢谢您了

**Comment by lxwkobe24** [comment]
> your command did not set `data_set` variable.

Traceback (most recent call last):
  File "main.py", line 455, in <module>
    main(args)
  File "main.py", line 207, in main
    dataset_train, args.nb_classes = build_dataset(is_train=True, args=args)
  File "/home/kas/ConvNeXt/datasets.py", line 42, in build_dataset
    assert len(dataset.class_to_idx) == nb_classes
AssertionError
您好，我设置了自己是10类，为啥还会报错呀~
