### ISSUE TITLE
KeyError: 'DistOptimizerHook is not in the hook registry'

### ISSUE THREAD

**Issue by sure7018** [facebookresearch/ConvNeXt#38]
Hello, when I was running the target detection code, the following problems occurred, which should be caused by the missing part of the files in mmdet / Models / detectors. Can you release the perfect code?

Traceback (most recent call last):
  File "tools/train.py", line 189, in <module>
    cfg.get('momentum_config', None))
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 540, in register_training_hooks
    main()
  File "tools/train.py", line 185, in main
    self.register_optimizer_hook(optimizer_config)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 448, in register_optimizer_hook
    meta=meta)
  File "/root/data/UniverseNet-master/mmdet/apis/train.py", line 166, in train_detector
    hook = mmcv.build_from_cfg(optimizer_config, HOOKS)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/registry.py", line 45, in build_from_cfg
        f'{obj_type} is not in the {registry.name} registry')cfg.get('momentum_config', None))

  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 540, in register_training_hooks
KeyError: 'DistOptimizerHook is not in the hook registry'

**Comment by HannaMao** [comment]
Thanks for reporting this! We actually didn't observe the issue on our side. 

Do you have `/mmdet/utils/optimizer.py` file in your folder? It should be there if you follow the instructions here `https://github.com/facebookresearch/ConvNeXt/tree/main/object_detection`

**Comment by github-eliviate** [comment]
> Thanks for reporting this! We actually didn't observe the issue on our side.
> 
> Do you have `/mmdet/utils/optimizer.py` file in your folder? It should be there if you follow the instructions here `https://github.com/facebookresearch/ConvNeXt/tree/main/object_detection`

yes. what is the version of your mmcv?

**Comment by HannaMao** [comment]
We use mmcv 1.3.0, mmdet 2.11.0, and timm 0.3.2.
