### ISSUE TITLE
I add the configs and models of ConvNeXt to the Swin-Transformer-Object-Detection.

### ISSUE THREAD

**Issue by Williamlizl** [facebookresearch/ConvNeXt#67]
I add the configs and models of ConvNeXt to the Swin-Transformer-Object-Detection.
[https://github.com/SwinTransformer/Swin-Transformer-Object-Detection/issues](url)
then i run the commond: 
`CUDA_VISIBLE_DEVICES=0,1,2,3 ./tools/dist_train.sh ./configs/convnext/cascade_mask_rcnn_convnext_large_patch4_window7_mstrain_480-800_giou_4conv1f_adamw_3x_coco_in22k.py 4 --cfg-options model.pretrained='/home/lbc/Swin-Transformer-Object-Detection/pretrained/convnext_large_22k_1k_384.pth'`

the error is:

`Traceback (most recent call last):
  File "/home/lbc/.local/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/lbc/Swin-Transformer-Object-Detection/mmdet/models/detectors/cascade_rcnn.py", line 25, in __init__
    pretrained=pretrained)
  File "/home/lbc/Swin-Transformer-Object-Detection/mmdet/models/detectors/two_stage.py", line 26, in __init__
    self.backbone = build_backbone(backbone)
  File "/home/lbc/Swin-Transformer-Object-Detection/mmdet/models/builder.py", line 39, in build_backbone
    return build(cfg, BACKBONES)
  File "/home/lbc/Swin-Transformer-Object-Detection/mmdet/models/builder.py", line 34, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/lbc/.local/lib/python3.7/site-packages/mmcv/utils/registry.py", line 45, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'ConvNeXt is not in the backbone registry'
`

**Comment by maxisawesome** [comment]
I am also getting this error, after moving all convnext code into swintransformer and changing imports, etc

**Comment by joeyslv** [comment]
hi did you figure it out?

**Comment by HannaMao** [comment]
Please refer to https://github.com/facebookresearch/ConvNeXt/issues/81#issue-1174175800 for discussions.
