### ISSUE TITLE
'ConvNeXt is not in the models registry' . How to register the ConvNeXt ,i add the all files to Swin-T ，but did not work

### ISSUE THREAD

**Issue by joeyslv** [facebookresearch/ConvNeXt#81]
```
custom_hooks = [dict(type='NumClassCheckHook')]
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
classes = ('loose_l', 'loose_s', 'poor_l', 'porous')
work_dir = './work_dirs\radar_convnext'
gpu_ids = range(0, 1)
  File "D:\App\anaconda\envs\convnext\lib\site-packages\mmcv\utils\registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "D:\App\anaconda\envs\convnext\lib\site-packages\mmcv\cnn\builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "D:\App\anaconda\envs\convnext\lib\site-packages\mmcv\utils\registry.py", line 45, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'ConvNeXt is not in the models registry'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 187, in <module>
    main()
  File "tools/train.py", line 161, in main
    test_cfg=cfg.get('test_cfg'))
  File "D:\App\anaconda\envs\convnext\lib\site-packages\mmdet\models\builder.py", line 59, in build_detector
    cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "D:\App\anaconda\envs\convnext\lib\site-packages\mmcv\utils\registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "D:\App\anaconda\envs\convnext\lib\site-packages\mmcv\cnn\builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "D:\App\anaconda\envs\convnext\lib\site-packages\mmcv\utils\registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "CascadeRCNN: 'ConvNeXt is not in the models registry'"
```

**Comment by joeyslv** [comment]
this is my envs :

```
2022-03-19 12:54:58,420 - mmdet - INFO - Environment info:
------------------------------------------------------------
sys.platform: win32
Python: 3.7.11 (default, Jul 27 2021, 09:42:29) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
GPU 0: NVIDIA GeForce RTX 3070 Laptop GPU
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1
NVCC: Build cuda_11.1.relgpu_drvr455TC455_06.29190527_0
GCC: gcc (Rev2, Built by MSYS2 project) 10.3.0
PyTorch: 1.9.0+cu111
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 2019
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=C:/w/b/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/w/b/windows/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, 

TorchVision: 0.10.0+cu111
OpenCV: 4.5.5
MMCV: 1.4.1
MMCV Compiler: MSVC 192930137
MMCV CUDA Compiler: 11.1
MMDetection: 2.22.0+
```

**Comment by HannaMao** [comment]
Did you add this file https://github.com/facebookresearch/ConvNeXt/blob/main/object_detection/mmdet/models/backbones/__init__.py to the corresponding location?

**Comment by joeyslv** [comment]
> Did you add this file https://github.com/facebookresearch/ConvNeXt/blob/main/object_detection/mmdet/models/backbones/__init__.py to the corresponding location?

yes ,i did !  i add it to Swin-T^s project  in `mmdet\models\backbones\__init__.py` 

```
from .darknet import Darknet
from .detectors_resnet import DetectoRS_ResNet
from .detectors_resnext import DetectoRS_ResNeXt
from .hourglass import HourglassNet
from .hrnet import HRNet
from .regnet import RegNet
from .res2net import Res2Net
from .resnest import ResNeSt
from .resnet import ResNet, ResNetV1d
from .resnext import ResNeXt
from .ssd_vgg import SSDVGG
from .trident_resnet import TridentResNet
from .swin_transformer import SwinTransformer
from .convnext import ConvNeXt

__all__ = [
    'RegNet', 'ResNet', 'ResNetV1d', 'ResNeXt', 'SSDVGG', 'HRNet', 'Res2Net',
    'HourglassNet', 'DetectoRS_ResNet', 'DetectoRS_ResNeXt', 'Darknet',
    'ResNeSt', 'TridentResNet', 'SwinTransformer', 'ConvNeXt'
]
```
but it seems to find ConvNeXt from the package mmdet-2.22

**Comment by HannaMao** [comment]
maybe try the suggestion here https://github.com/SwinTransformer/Swin-Transformer-Object-Detection/issues/59? Let me know if it resolves the issue?

**Comment by joeyslv** [comment]
> maybe try the suggestion here [SwinTransformer/Swin-Transformer-Object-Detection#59](https://github.com/SwinTransformer/Swin-Transformer-Object-Detection/issues/59)? Let me know if it resolves the issue!

it works ,  i can get the infomation of the Net , but i get a new error :
```
 Traceback (most recent call last):
  File "tools/train.py", line 187, in <module>
    main()
  File "tools/train.py", line 183, in main
    meta=meta)
  File "e:\object-detection\github\radar-convnext-detection\mmdet\apis\train.py", line 185, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "D:\App\anaconda\envs\ConveNeXt\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "D:\App\anaconda\envs\ConveNeXt\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "D:\App\anaconda\envs\ConveNeXt\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "D:\App\anaconda\envs\ConveNeXt\lib\site-packages\mmcv\parallel\data_parallel.py", line 75, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "e:\object-detection\github\radar-convnext-detection\mmdet\models\detectors\two_stage.py", line 156, in forward_train
    proposal_cfg=proposal_cfg)
  File "e:\object-detection\github\radar-convnext-detection\mmdet\models\dense_heads\base_dense_head.py", line 58, in forward_train
    proposal_list = self.get_bboxes(*outs, img_metas, cfg=proposal_cfg)
  File "D:\App\anaconda\envs\ConveNeXt\lib\site-packages\mmcv\runner\fp16_utils.py", line 186, in new_func
    return old_func(*args, **kwargs)
  File "e:\object-detection\github\radar-convnext-detection\mmdet\models\dense_heads\anchor_head.py", line 584, in get_bboxes
    scale_factors, cfg, rescale)
  File "e:\object-detection\github\radar-convnext-detection\mmdet\models\dense_heads\rpn_head.py", line 234, in _get_bboxes
    cfg.nms)
  File "D:\App\anaconda\envs\ConveNeXt\lib\site-packages\mmcv\ops\nms.py", line 307, in batched_nms
    dets, keep = nms_op(boxes_for_nms, scores, **nms_cfg_)
  File "D:\App\anaconda\envs\ConveNeXt\lib\site-packages\mmcv\utils\misc.py", line 340, in new_func
    output = old_func(*args, **kwargs)
  File "D:\App\anaconda\envs\ConveNeXt\lib\site-packages\mmcv\ops\nms.py", line 172, in nms
    score_threshold, max_num)
  File "D:\App\anaconda\envs\ConveNeXt\lib\site-packages\mmcv\ops\nms.py", line 27, in forward
    bboxes, scores, iou_threshold=float(iou_threshold), offset=offset)
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```
it looks like pytorch and CUDA versions don't match . to my confusion, I can run the same pytorch and CUDA in another project with similar env

**Comment by joeyslv** [comment]
when i use this env to run ssd300-detection , another one error:
```
loading annotations into memory...
Done (t=0.02s)
creating index...
index created!
fatal: not a git repository (or any of the parent directories): .git
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Traceback (most recent call last):
  File "tools/train.py", line 187, in <module>
    main()
  File "tools/train.py", line 183, in main
    meta=meta)
  File "e:\object-detection\github\radar-convnext-detection\mmdet\apis\train.py", line 178, in train_detector
    hook = build_from_cfg(hook_cfg, HOOKS)
  File "D:\App\anaconda\envs\ConveNeXt\lib\site-packages\mmcv\utils\registry.py", line 45, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'CheckInvalidLossHook is not in the hook registry'
```
I'm about to cry....

**Comment by joeyslv** [comment]
> now i can run ssd300-detection after i modify the 
```
custom_hooks = [
    dict(type='NumClassCheckHook'),
    dict(type='CheckInvalidLossHook', interval=50, priority='VERY_LOW')
]
```
to
```
custom_hooks = [
    dict(type='NumClassCheckHook'),
    dict(type='TextLoggerHook', interval=50, priority='VERY_LOW')
]
```
in config file , but run ConvNeXt detection is still CUDA error ,i guess the mmdet^s version is too old, Swin-T has a 2.11mmdetversion but the last is 2.22

**Comment by joeyslv** [comment]
i use ↓ code to find a specific error explain
```
import os
os.environ['CUDA_LAUNCH_BLOCKING'] = '1'
```
However , i dont kown how to fix it
`TypeError: can't pickle module objects`

**Comment by joeyslv** [comment]
```
(ConveNeXt) E:\Object-Detection\Github\radar-ConvNeXt-detection>python tools/train.py myconfig/radar_convnext.py
apex is not installed
apex is not installed
apex is not installed
apex is not installed
Traceback (most recent call last):
  File "tools/train.py", line 187, in <module>
    main()
  File "tools/train.py", line 89, in main
    cfg = Config.fromfile(args.config)
  File "D:\App\anaconda\envs\ConveNeXt\lib\site-packages\mmcv\utils\config.py", line 332, in fromfile
    use_predefined_variables)
  File "D:\App\anaconda\envs\ConveNeXt\lib\site-packages\mmcv\utils\config.py", line 262, in _file2dict
    base_cfg_dict)
  File "D:\App\anaconda\envs\ConveNeXt\lib\site-packages\mmcv\utils\config.py", line 149, in _substitute_base_vars
    cfg = copy.deepcopy(cfg)
  File "D:\App\anaconda\envs\ConveNeXt\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "D:\App\anaconda\envs\ConveNeXt\lib\copy.py", line 241, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "D:\App\anaconda\envs\ConveNeXt\lib\copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle module objects
```
its so bad

**Comment by HannaMao** [comment]
I would suggest you install mmdet 2.11.0 and mmcv 1.3.0 in this case. I highly suspect the errors you showed above are due to environment misconfiguration. Closing the current issue now. Please let us know if you have other questions.

**Comment by joeyslv** [comment]
I follow your  suggest that install mmdet 2.11.0 and mmcv 1.3.0 ,but it cant read the Config file
```
(ConveNeXt) E:\Object-Detection\Github\radar-ConvNeXt-detection>python tools/train.py myconfig/radar_convnext.py
apex is not installed
apex is not installed
apex is not installed
apex is not installed
Traceback (most recent call last):
  File "tools/train.py", line 187, in <module>
    main()
  File "tools/train.py", line 89, in main
    cfg = Config.fromfile(args.config)
  File "D:\App\anaconda\envs\ConveNeXt\lib\site-packages\mmcv\utils\config.py", line 252, in fromfile
    use_predefined_variables)
  File "D:\App\anaconda\envs\ConveNeXt\lib\site-packages\mmcv\utils\config.py", line 138, in _file2dict
    temp_config_file.name)
  File "D:\App\anaconda\envs\ConveNeXt\lib\site-packages\mmcv\utils\config.py", line 113, in _substitute_predefined_vars
    config_file = f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaa in position 34: illegal multibyte sequence
```
